### PR TITLE
Update the sourcecred dependency

### PR DESCRIPTION
**Pull request by Beanow**
Now using v0.3.0 (Timeline cred) as the base.
Still includes some modifications from my fork to:
- Allow weight overrides during build-time.
- Increase number of entries shown in tables and charts.

### CODE REVIEW

**Comment by Beanow** [comment]
An impression of the new timeline version.
Note the previous calculation and display method is still available under the "(legacy)" link.

timeline preview

**Comment by vsoch** [comment]
Oh that's super cool :)

**Comment by Beanow** [comment]
Rebased and changed the sourcecred submodule to no longer use my early custom-weights hack, but the one created for a `--weights` PR upstream.

**Comment by Beanow** [comment]
Final update to include --weights as merged into upstream master.

**Comment by Beanow** [comment]
As this provides just more data and features without losing the legacy one, I'll go ahead and merge this.

**Pull request merged**
